weather:
    baseUrl: https://weatherapi-com.p.rapidapi.com/current.json?q=Pretoria
    X-RapidAPI-Key: "733d6caf44msh8e51dbcede9e0f8p1b2b12jsne27ab69a884c"
    X-RapidAPI-Host: weatherapi-com.p.rapidapi.com

    items-per-page: 10
    validity-time: 5

spring:
    profiles:
        active: "pod"

