cats:
    baseUrl: https://api.thecatapi.com/v1/images/search
    x-api-key: live_vzOdl14dU8CHv3FzcUR7mWvYminA8q09RfEpGn8ilc3hgDbJ3MDlmZjcgXRAdZ6h
    limit: 10
    breed_ids: beng
    validity-time: 5

spring:
    profiles:
        active: "pod"

