swagger: '2.0'
info:
  description: Cats images
  version: '0.1'
  title: Cats
tags:
  - name: Cats
security:
  ApiKey:
    type: api_key
    in: query
    name: api_key
paths:
  /cats:
    get:
      tags:
        - Cats
      produces:
        - application/json
      parameters:
        - in: query
          name: limit
          type: number
          required: true
        - in: query
          name: breed_ids
          type: string
          required: true
      responses:
        '200':
          description: OK Success
          schema:
            $ref: '#/definitions/theCatsResponse'
  /cats/findById:
    get:
      tags:
        - Cats
      summary: Finds cat by id
      description: Finds cat by id
      operationId: findCatById
      produces:
        - application/json
      parameters:
        - in: query
          name: limit
          type: number
          required: true
        - in: query
          name: breed_ids
          type: string
          required: true
        - name: id
          in: query
          description: id to filter by
          required: true
          type: string
      responses:
        '200':
          description: OK Success
          schema:
            $ref: '#/definitions/theCatsResponse'
definitions:
  theCatsResponse:
    type: array
    items:
      type: object
      properties:
          breeds:
            type: array
            items:
              type: object
              properties:
                weight:
                  type: object
                  properties:
                    imperial:
                      type: string
                    metric:
                      type: string
                id:
                 type: string
                name:
                   type: string
                cfa_url:
                  type: string
                vetstreet_url:
                  type: string
                vcahospitals_url:
                  type: string
                temperament:
                  type: string
                country_codes:
                  type: string
                country_code:
                  type: string
                description:
                  type: string
                life_span:
                  type: string
                indoor:
                  type: number
                lap:
                  type: number
                adaptability:
                  type: number
                affection_level:
                  type: number
                child_friendly:
                  type: number
                cat_friendly:
                  type: number
                dog_friendly:
                  type: number
                energy_level:
                  type: number
                grooming:
                  type: number
                health_issues:
                  type: number
                intelligence:
                  type: number
                shedding_level:
                  type: number
                social_needs:
                  type: number
                stranger_friendly:
                  type: number
                vocalisation:
                  type: number
                bidability:
                  type: number
                experimental:
                  type: number
                hairless:
                  type: number
                natural:
                  type: number
                rare:
                  type: number
                rex:
                  type: number
                suppressed_tail:
                  type: number
                short_legs:
                  type: number
                wikipedia_url:
                  type: number
                hypoallergenic:
                  type: string
                reference_image_id:
                  type: string
          id:
            type: string
          url:
            type: string
          width:
            type: number
          height:
            type: number
