swagger: '2.0'
info:
  description: Hello World
  version: '0.1'
  title: Hello World
tags:
  - name: helloWorld
host: localhost:8080
basePath: /api/v2
schemes:
  - http
paths:
  /helloWorld:
    get:
      summary: Get Text
      operationId: getText
      tags:
        - helloWorld
      produces:
        - application/json
      responses:
        '200':
          description: Ok, successful
          schema:
            $ref: '#/definitions/helloWorld'

definitions:
  helloWorld:
    type: object
    properties:
      name:
        type: string
